# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
workspace 'HaQ'
target 'HaQ' do
pod 'Parse'
pod 'GoogleMaps'
pod 'MBProgressHUD', '~> 0.9.2'
end

